# netlify.toml
# Diese Konfigurationsdatei wird f端r das Deployment auf Netlify verwendet
# Sie definiert Build-Einstellungen, Weiterleitungsregeln und CMS-Konfiguration

[build]
  publish = "dist"
  command = "npm run build"

# Weiterleitungsregeln f端r SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Umgebungsvariablen f端r die Produktion
[context.production.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

# Spezielle Build-Einstellungen f端r TypeScript
[build.environment]
  VITE_DISABLE_ESLINT_PLUGIN = "true"
